# Generated by Django 6.0.6 on 2026-06-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('level', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=100)),
                ('roadmap_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='career.roadmapsession')),
            ],
        ),
    ]
