# Generated by Django 6.0.6 on 2026-06-06 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('topic', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='career.roadmapsession')),
            ],
            options={
                'unique_together': {('session', 'month', 'week', 'topic')},
            },
        ),
    ]
