# Generated by Django 6.0.6 on 2026-06-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_covered', models.JSONField()),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('score', models.IntegerField()),
                ('weak_areas', models.JSONField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='career.roadmapsession')),
            ],
        ),
    ]
